### ISSUE TITLE
Scope: Discord or Beyond?

### ISSUE THREAD

**Issue by sommersoft** [adafruit/Adafruit_Community_Code_of_Conduct#2]
I know its still a work-in-progress and this may work itself out, but the scoping statements are confusing.

The repo and document title define it as the Discord CoC, and use of "On Discord" or Discord-centric terminology is used throughout the document without contrasting definitions (e.g. "On the forums").

Then, at the end of the document there is this statement:
> The enforcement policies listed above apply to all official Adafruit venues. This includes but is not limited to the entire Adafruit Discord server, GitHub repositories under Adafruit, and all forums under forums.adafruit.com.

Again, I know this may work itself out. Or may be a small cog in a larger machine that I'm not aware of. Just confusion that I think could be addressed.

**Comment by tannewt** [comment]
I'd like this to apply to all members who participate CircuitPython official spaces and their behavior (both public and private).

Adafruit's spaces are covered by the "Be excellent" policy here too: https://www.adafruit.com/terms_of_service

**Comment by kattni** [comment]
I agree entirely with both of these suggestions. I'm removing the wording regarding forums as that is covered by Adafruit's Be Excellent policy, and limiting the scope of the GitHub repos to CircuitPython since that is what we are moderating. 

We have to walk a line between having this apply solely to CircuitPython related spaces, and the entirety of Discord, since Discord is a huge part of this and as a whole it is not CP specific. I'm now working on wording it to include both of these things without limiting the scope. I am also working on making the bigger picture flow better heading into and including the scope statements.

**Comment by kattni** [comment]
Updated wording to better reflect applying to CircuitPython spaces. PR incoming. Closing issue.
